-- CLAVES PRIMARIAS
ALTER TABLE dbo.CARRERAS ADD CONSTRAINT
	PK_CARRERAS PRIMARY KEY CLUSTERED 
	(
	carrera_id
	) ON [PRIMARY]
GO
ALTER TABLE dbo.CURSOS ADD CONSTRAINT
	PK_CURSOS PRIMARY KEY CLUSTERED 
	(
	curso_id
	) ON [PRIMARY]
GO
ALTER TABLE dbo.PROFESORES ADD CONSTRAINT
	PK_PROFESORES PRIMARY KEY CLUSTERED 
	(
	prof_id
	)  ON [PRIMARY]
GO

-- CLAVES FORANEAS
ALTER TABLE dbo.CURSOS ADD CONSTRAINT
	FK_CURSOS_PROFESORES FOREIGN KEY
	(
	prof_id
	) REFERENCES dbo.PROFESORES
	(
	prof_id
	) 
GO	
ALTER TABLE dbo.PROFESORES ADD CONSTRAINT
	FK_PROFESORES_CARRERAS FOREIGN KEY
	(
	carrera_id
	) REFERENCES dbo.CARRERAS
	(
	carrera_id
	)
GO
